from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.accueil, name='accueil'),
    path('apropos/', views.apropos, name='apropos'),
    path('historique/', views.historique, name='historique'),
    path('objectif-general/', views.objectif_general, name='objectif_general'),
    path('objectif-specifique/', views.objectif_specifique, name='objectif_specifique'),
    path('gestion/', views.gestion, name='gestion'),
    path('eglises/', views.eglises, name='eglises'),
    path('eglises/ajout/', views.ajout_eglise, name='ajout_eglise'),
    path('eglises/modifier/<int:eglise_id>/', views.modifier_eglise, name='modifier_eglise'),
    path('eglises/supprimer/<int:eglise_id>/', views.supprimer_eglise, name='supprimer_eglise'),
    path('eglises/visite/', views.visite_pastorale, name='visite_pastorale'),
    path('eglises/projet/', views.projet_local, name='projet_local'),
    path('personnel-pastoral/', views.personnel_pastoral, name='personnel_pastoral'),
    path('personnel-pastoral/voir/', views.voir_personnel_pastoral, name='voir_personnel_pastoral'),
    path('get_pasteur_details/<int:pasteur_id>/', views.get_pasteur_details, name='get_pasteur_details'),
    path('personnel-pastoral/modifier/<int:pasteur_id>/', views.modifier_pasteur, name='modifier_pasteur'),
    path('personnel-pastoral/supprimer/<int:pasteur_id>/', views.supprimer_pasteur, name='supprimer_pasteur'),
    # path('update_pasteur/<int:pasteur_id>/', views.update_pasteur, name='update_pasteur'),
    # path('delete_pasteur/<int:pasteur_id>/', views.delete_pasteur, name='delete_pasteur'),
    path('get_eglise_by_name/', views.get_eglise_by_name, name='get_eglise_by_name'),
    path('les-membres/', views.les_membres, name='les_membres'),
    path('membres-eglise/', views.membres_eglise, name='membres_eglise'),
    path('membres-eglise/ajout/', views.ajouter_membre, name='ajouter_membre'),
    path('membres-eglise/supprimer/<int:membre_id>/', views.supprimer_membre, name='supprimer_membre'),
    path('membres-eglise/details/<int:membre_id>/', views.details_membre, name='details_membre'),
    path('membres-eglise/modifier/<int:membre_id>/', views.modifier_membre, name='modifier_membre'),
    path('api/membres/', views.api_membres, name='api_membres'),
    path('departements/', views.departements, name='departements'),
    path('voir_departements/', views.voir_departements, name='voir_departements'),
    path('departements/modifier/<int:departement_id>/', views.modifier_departement, name='modifier_departement'),
    path('departements/supprimer/<int:departement_id>/', views.supprimer_departement, name='supprimer_departement'),
    path('departements/attachments/supprimer/<int:attachment_id>/', views.supprimer_departement_attachment, name='supprimer_departement_attachment'),
    path('finances/', views.finances, name='finances'),
    path('banque/', views.banque, name='banque'),
    path('banque/enregistrements/', views.banque_records_all, name='banque_records_all'),
    path('supprimer-rapport-banque/<int:rapport_id>/', views.supprimer_rapport_banque, name='supprimer_rapport_banque'),
    path('comptabilite/', views.comptabilite, name='comptabilite'),
    path('supprimer-rapport-comptabilite/<int:rapport_id>/', views.supprimer_rapport_comptabilite, name='supprimer_rapport_comptabilite'),
    path('finances/enregistrements/', views.finances_records_all, name='finances_records_all'),
    path('nos-fideles/', views.nos_fideles, name='nos_fideles'),
    path('actualite/', views.actualite, name='actualite'),
    path('evenements/', views.evenements, name='evenements'),
    path('effectifs-culte/complet/', views.effectifs_culte_complet, name='effectifs_culte_complet'),
    path('planification/', views.planification, name='planification'),
    path('planification/complet/', views.planification_complet, name='planification_complet'),
    # API Effectifs du culte
    path('api/culte/effectifs/enregistrer/', views.enregistrer_effectif_culte, name='enregistrer_effectif_culte'),
    path('api/culte/effectifs/', views.lister_effectifs_culte, name='lister_effectifs_culte'),
    path('api/culte/effectifs/export.xls', views.exporter_effectifs_culte_excel, name='exporter_effectifs_culte_excel'),
    path('api/culte/effectifs/export.xlsx', views.exporter_effectifs_culte_xlsx, name='exporter_effectifs_culte_xlsx'),
    path('api/culte/effectifs/export.pdf', views.exporter_effectifs_culte_pdf, name='exporter_effectifs_culte_pdf'),
    path('api/culte/effectifs/<int:eff_id>/supprimer/', views.supprimer_effectif_culte, name='supprimer_effectif_culte'),
    path('api/culte/effectifs/<int:eff_id>/modifier/', views.modifier_effectif_culte, name='modifier_effectif_culte'),
    # API Églises (liste) et Départements (liste)
    path('api/eglises/', views.api_eglises_list, name='api_eglises_list'),
    path('api/departements/', views.api_departements_list, name='api_departements_list'),
    # API Planification stratégique (StrategicPlan)
    path('api/sp/', views.api_sp_list, name='api_sp_list'),
    path('api/sp/create/', views.api_sp_create, name='api_sp_create'),
    path('api/sp/<int:item_id>/update/', views.api_sp_update, name='api_sp_update'),
    path('api/sp/<int:item_id>/delete/', views.api_sp_delete, name='api_sp_delete'),
    path('api/sp/export.csv', views.api_sp_export_csv, name='api_sp_export_csv'),
    path('api/sp/export.xlsx', views.api_sp_export_xlsx, name='api_sp_export_xlsx'),
    path('api/sp/export.pdf', views.api_sp_export_pdf, name='api_sp_export_pdf'),
    path('suivi-presences/', views.suivi_presences, name='suivi_presences'),
    path('archivage-rapports/', views.archivage_rapports, name='archivage_rapports'),
    path('communication/', views.communication, name='communication'),
    path('contact/', views.contact, name='contact'),
    path('biographie-pasteurs/', views.biographie_pasteurs, name='biographie_pasteurs'),
    path('statut-reglements/', views.statut_reglements, name='statut_reglements'),
    path('plan-strategique/', views.plan_strategique, name='plan_strategique'),
    path('test-image/', views.test_image, name='test_image'),
    # Finances: actions
    path('finances/operation/modifier/<int:operation_id>/', views.modifier_finance, name='finance_edit'),
    path('finances/operation/supprimer/<int:operation_id>/', views.supprimer_finance, name='finance_delete'),
    path('finances/operations/supprimer-tout/', views.supprimer_toutes_finances, name='finance_delete_all'),
    path('finances/rapport/modifier/<int:report_id>/', views.modifier_finance_report, name='finance_report_edit'),
    path('finances/rapport/supprimer/<int:report_id>/', views.supprimer_finance_report, name='finance_report_delete'),
    path('finances/rapport/<int:report_id>/', views.finance_report_detail, name='finance_report_detail'),
]

