# Generated by Django 5.2.3 on 2025-07-02 17:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eglise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('adresse', models.CharField(max_length=200, verbose_name='Adresse')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='Guinée', max_length=100, verbose_name='Pays')),
                ('date_creation', models.DateField(verbose_name='Date de création')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('responsable', models.CharField(max_length=100, verbose_name='Responsable')),
                ('nombre_membres', models.PositiveIntegerField(default=0, verbose_name='Nombre de membres')),
            ],
            options={
                'verbose_name': 'Église',
                'verbose_name_plural': 'Églises',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du département')),
                ('responsable', models.CharField(max_length=100, verbose_name='Responsable')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eglise', verbose_name='Église')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('depense', 'Dépense'), ('recette', 'Recette')], max_length=10, verbose_name="Type d'opération")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant')),
                ('date_operation', models.DateField(verbose_name="Date de l'opération")),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('beneficiaire', models.CharField(blank=True, max_length=100, verbose_name='Bénéficiaire')),
                ('categorie', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eglise', verbose_name='Église')),
            ],
            options={
                'verbose_name': 'Opération Financière',
                'verbose_name_plural': 'Opérations Financières',
                'ordering': ['-date_operation'],
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('adresse', models.CharField(max_length=200, verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profession')),
                ('date_bapteme', models.DateField(blank=True, null=True, verbose_name='Date de baptême')),
                ('lieu_bapteme', models.CharField(blank=True, max_length=100, verbose_name='Lieu de baptême')),
                ('date_adhesion', models.DateField(verbose_name="Date d'adhésion")),
                ('etat_civil', models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], max_length=20, verbose_name='État civil')),
                ('nom_conjoint', models.CharField(blank=True, max_length=100, verbose_name='Nom du conjoint')),
                ('nombre_enfants', models.PositiveIntegerField(default=0, verbose_name="Nombre d'enfants")),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eglise', verbose_name='Église')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelPastoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('poste', models.CharField(max_length=100, verbose_name='Poste')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eglise', verbose_name='Église')),
            ],
            options={
                'verbose_name': 'Personnel Pastoral',
                'verbose_name_plural': 'Personnel Pastoral',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
