# Generated by Django 5.2.3 on 2025-07-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eglise',
            name='activites',
            field=models.TextField(blank=True, help_text='Liste des activités séparées par des virgules', verbose_name='Activités'),
        ),
        migrations.AddField(
            model_name='eglise',
            name='autres_activites_detail',
            field=models.TextField(blank=True, verbose_name='Détails des autres activités'),
        ),
        migrations.AddField(
            model_name='eglise',
            name='date_declaration',
            field=models.DateField(blank=True, null=True, verbose_name='Date de déclaration'),
        ),
        migrations.AddField(
            model_name='eglise',
            name='date_enregistrement',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'enregistrement"),
        ),
        migrations.AddField(
            model_name='eglise',
            name='est_association',
            field=models.BooleanField(default=False, verbose_name='Est une association enregistrée'),
        ),
        migrations.AddField(
            model_name='eglise',
            name='membres_fondateurs_doc',
            field=models.FileField(blank=True, null=True, upload_to='eglises/documents/', verbose_name='Document des membres fondateurs'),
        ),
        migrations.AddField(
            model_name='eglise',
            name='nom_declarant',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom du déclarant'),
        ),
        migrations.AddField(
            model_name='eglise',
            name='numero_enregistrement',
            field=models.CharField(blank=True, max_length=100, verbose_name="Numéro d'enregistrement"),
        ),
        migrations.AddField(
            model_name='eglise',
            name='pieces_identite_doc',
            field=models.FileField(blank=True, null=True, upload_to='eglises/documents/', verbose_name="Pièces d'identité"),
        ),
        migrations.AddField(
            model_name='eglise',
            name='preuve_adresse_doc',
            field=models.FileField(blank=True, null=True, upload_to='eglises/documents/', verbose_name="Preuve d'adresse"),
        ),
        migrations.AddField(
            model_name='eglise',
            name='qualite_declarant',
            field=models.CharField(blank=True, max_length=100, verbose_name='Qualité du déclarant'),
        ),
        migrations.AddField(
            model_name='eglise',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quartier'),
        ),
        migrations.AddField(
            model_name='eglise',
            name='statuts_doc',
            field=models.FileField(blank=True, null=True, upload_to='eglises/documents/', verbose_name='Document des statuts'),
        ),
    ]
