# Generated by Django 5.2.3 on 2025-07-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_eglise_activites_eglise_autres_activites_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eglise',
            name='adresse',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse'),
        ),
    ]
