# Generated by Django 5.2.3 on 2025-07-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_eglise_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnelpastoral',
            name='date_embauche',
        ),
        migrations.RemoveField(
            model_name='personnelpastoral',
            name='poste',
        ),
        migrations.AddField(
            model_name='personnelpastoral',
            name='date_affectation',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'affectation"),
        ),
        migrations.AddField(
            model_name='personnelpastoral',
            name='date_consecration',
            field=models.DateField(blank=True, null=True, verbose_name='Date de consécration'),
        ),
        migrations.AddField(
            model_name='personnelpastoral',
            name='document_fichier',
            field=models.FileField(blank=True, null=True, upload_to='personnel/documents/', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='personnelpastoral',
            name='domicile',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicile'),
        ),
        migrations.AddField(
            model_name='personnelpastoral',
            name='etat_civil',
            field=models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], max_length=20, null=True, verbose_name='État civil'),
        ),
        migrations.AddField(
            model_name='personnelpastoral',
            name='fonction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonction'),
        ),
        migrations.AddField(
            model_name='personnelpastoral',
            name='lieu_affectation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Lieu d'affectation"),
        ),
        migrations.AddField(
            model_name='personnelpastoral',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='personnelpastoral',
            name='nationalite',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationalité'),
        ),
        migrations.AddField(
            model_name='personnelpastoral',
            name='nombre_enfants',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Nombre d'enfants"),
        ),
        migrations.AddField(
            model_name='personnelpastoral',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='personnel/photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='personnelpastoral',
            name='prenoms_nom_mere',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénoms & Nom de la Mère'),
        ),
        migrations.AddField(
            model_name='personnelpastoral',
            name='prenoms_pere',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénoms du Père'),
        ),
        migrations.AddField(
            model_name='personnelpastoral',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='personnelpastoral',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Région'),
        ),
        migrations.AddField(
            model_name='personnelpastoral',
            name='statut_actuel',
            field=models.CharField(blank=True, choices=[('pasteur_principal', 'Pasteur Principal'), ('pasteur_assistant', 'Pasteur Assistant'), ('pasteur_stagiaire', 'Pasteur Stagiaire'), ('evangeliste', 'Évangéliste'), ('diacre', 'Diacre'), ('ancien', 'Ancien')], max_length=50, null=True, verbose_name='Statut actuel'),
        ),
        migrations.AddField(
            model_name='personnelpastoral',
            name='types_formations',
            field=models.TextField(blank=True, null=True, verbose_name='Types de formations'),
        ),
        migrations.AddField(
            model_name='personnelpastoral',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='personnelpastoral',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
    ]
