# Generated by Django 5.2.3 on 2025-08-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_add_consecration_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eglise',
            name='numero_enregistrement',
        ),
        migrations.AddField(
            model_name='eglise',
            name='numero_autorisation',
            field=models.CharField(blank=True, max_length=100, verbose_name="Numéro d'autorisation"),
        ),
    ]
