# Generated by Django 5.2.3 on 2025-08-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_add_est_association_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='montant_souhaite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant souhaité'),
        ),
        migrations.AddField(
            model_name='membre',
            name='motivation',
            field=models.TextField(blank=True, verbose_name='Motivation'),
        ),
        migrations.AddField(
            model_name='membre',
            name='services',
            field=models.TextField(blank=True, help_text='Liste séparée par des virgules', verbose_name='Services'),
        ),
        migrations.AddField(
            model_name='membre',
            name='soutien_financier',
            field=models.BooleanField(default=False, verbose_name='Soutien financier'),
        ),
    ]
