# Generated by Django 5.2.3 on 2025-08-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_add_membre_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='certificat_bapteme',
            field=models.FileField(blank=True, null=True, upload_to='personnel/documents/', verbose_name='Certificat de baptême'),
        ),
        migrations.AddField(
            model_name='membre',
            name='piece_identite',
            field=models.FileField(blank=True, null=True, upload_to='personnel/documents/', verbose_name="Pièce d'identité"),
        ),
    ]
