# Generated by Django 5.2.3 on 2025-08-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_membre_certificat_bapteme_membre_piece_identite'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='activites_majeures',
            field=models.TextField(blank=True, null=True, verbose_name='Activités majeures (liste)'),
        ),
        migrations.AddField(
            model_name='departement',
            name='besoins_prioritaires',
            field=models.TextField(blank=True, null=True, verbose_name='Besoins prioritaires'),
        ),
        migrations.AddField(
            model_name='departement',
            name='budget_annuel_estime',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Budget annuel estimé'),
        ),
        migrations.AddField(
            model_name='departement',
            name='date_creation',
            field=models.DateField(blank=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='departement',
            name='date_validation',
            field=models.DateField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='departement',
            name='membres_clefs',
            field=models.TextField(blank=True, null=True, verbose_name='Membres clés (CSV nom:fonction)'),
        ),
        migrations.AddField(
            model_name='departement',
            name='mission',
            field=models.TextField(blank=True, null=True, verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='departement',
            name='nombre_membres',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nombre de membres'),
        ),
        migrations.AddField(
            model_name='departement',
            name='objectifs_specifiques',
            field=models.TextField(blank=True, null=True, verbose_name='Objectifs spécifiques (liste)'),
        ),
        migrations.AddField(
            model_name='departement',
            name='observations_conseil',
            field=models.TextField(blank=True, null=True, verbose_name='Observations du Conseil'),
        ),
        migrations.AddField(
            model_name='departement',
            name='prochaine_activite_date',
            field=models.DateField(blank=True, null=True, verbose_name='Prochaine activité - Date'),
        ),
        migrations.AddField(
            model_name='departement',
            name='prochaine_activite_lieu',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Prochaine activité - Lieu'),
        ),
        migrations.AddField(
            model_name='departement',
            name='ressources_disponibles',
            field=models.TextField(blank=True, null=True, verbose_name='Ressources disponibles'),
        ),
        migrations.AddField(
            model_name='departement',
            name='statut_actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='departement',
            name='valide_par_conseil',
            field=models.BooleanField(default=False, verbose_name='Validé par le Conseil Pastoral'),
        ),
        migrations.AddField(
            model_name='departement',
            name='vision',
            field=models.TextField(blank=True, null=True, verbose_name='Vision'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='nom',
            field=models.CharField(max_length=150, verbose_name='Nom du département'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='responsable',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone'),
        ),
    ]
