# Generated by Django 5.2.3 on 2025-08-18 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_departement_activites_majeures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='departements/documents/', verbose_name='Fichier')),
                ('nom_original', models.CharField(blank=True, max_length=255, verbose_name='Nom original')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='main.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Pièce jointe de Département',
                'verbose_name_plural': 'Pièces jointes de Département',
                'ordering': ['-created_at'],
            },
        ),
    ]
