# Generated by Django 5.2.3 on 2025-08-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_departementattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='departement',
            field=models.TextField(blank=True, help_text='Ex: Chorale, Évangélisation', verbose_name='Départements où vous souhaitez servir'),
        ),
    ]
