# Generated by Django 5.2.3 on 2025-08-24 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_membre_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='justificatif_numero',
            field=models.CharField(blank=True, max_length=100, verbose_name='Justificatif (N°)'),
        ),
        migrations.AddField(
            model_name='finance',
            name='mode_paiement',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='finance',
            name='nature_depense',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nature dépense'),
        ),
        migrations.AddField(
            model_name='finance',
            name='remarques',
            field=models.TextField(blank=True, verbose_name='Remarques'),
        ),
        migrations.AddField(
            model_name='finance',
            name='source_revenu',
            field=models.CharField(blank=True, max_length=150, verbose_name='Source de revenu'),
        ),
        migrations.CreateModel(
            name='FinanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rapport', models.DateField(blank=True, null=True, verbose_name='Date du rapport')),
                ('periode_du', models.DateField(blank=True, null=True, verbose_name='Du')),
                ('periode_au', models.DateField(blank=True, null=True, verbose_name='Au')),
                ('responsable', models.CharField(blank=True, max_length=150, verbose_name='Responsable')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='Contact')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('total_recettes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total recettes')),
                ('total_depenses', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total dépenses')),
                ('solde_initial', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Solde initial')),
                ('solde_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Solde final')),
                ('verifie_par', models.CharField(blank=True, max_length=150, verbose_name='Vérifié par')),
                ('date_verification', models.DateField(blank=True, null=True, verbose_name='Date de vérification')),
                ('approuve_par', models.CharField(blank=True, max_length=150, verbose_name='Approuvé par')),
                ('nombre_pieces_jointes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pièces jointes')),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eglise', verbose_name='Église')),
            ],
            options={
                'verbose_name': 'Rapport Financier',
                'verbose_name_plural': 'Rapports Financiers',
                'ordering': ['-date_rapport', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, verbose_name='Nom')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='finances/pieces_jointes/', verbose_name='Fichier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='main.financereport', verbose_name='Rapport')),
            ],
            options={
                'verbose_name': 'Pièce justificative financière',
                'verbose_name_plural': 'Pièces justificatives financières',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='finance',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='main.financereport', verbose_name='Rapport financier'),
        ),
    ]
