# Generated by Django 5.2.3 on 2025-08-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_finance_justificatif_numero_finance_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financereport',
            name='beneficiaire',
            field=models.TextField(blank=True, help_text='Bénéficiaires séparés par des virgules', verbose_name='Bénéficiaire'),
        ),
        migrations.AddField(
            model_name='financereport',
            name='evenement',
            field=models.TextField(blank=True, help_text='Événements séparés par des virgules', verbose_name='Événement'),
        ),
        migrations.AddField(
            model_name='financereport',
            name='justificatif',
            field=models.TextField(blank=True, help_text='Justificatifs séparés par des virgules', verbose_name='Justificatif'),
        ),
        migrations.AddField(
            model_name='financereport',
            name='mode_paiement',
            field=models.TextField(blank=True, help_text='Modes de paiement séparés par des virgules', verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='financereport',
            name='nature_depense',
            field=models.TextField(blank=True, help_text='Natures de dépenses séparées par des virgules', verbose_name='Nature dépense'),
        ),
        migrations.AddField(
            model_name='financereport',
            name='source_revenu',
            field=models.TextField(blank=True, help_text='Sources de revenus séparées par des virgules', verbose_name='Source de revenu'),
        ),
    ]
