# Generated by Django 5.2.3 on 2025-08-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_financereport_beneficiaire_financereport_evenement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComptabiliteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eglise_nom', models.CharField(max_length=200)),
                ('periode', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('solde_initial', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_revenus', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_depenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('solde_final', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sources_revenus', models.TextField(blank=True)),
                ('dates_revenus', models.TextField(blank=True)),
                ('modes_paiement_revenus', models.TextField(blank=True)),
                ('evenements', models.TextField(blank=True)),
                ('natures_depenses', models.TextField(blank=True)),
                ('montants_depenses', models.TextField(blank=True)),
                ('beneficiaires', models.TextField(blank=True)),
                ('justificatifs', models.TextField(blank=True)),
                ('categories', models.TextField(blank=True)),
                ('nb_pj', models.IntegerField(default=0)),
                ('verifie_par', models.CharField(blank=True, max_length=100)),
                ('approuve_par', models.CharField(blank=True, max_length=100)),
                ('date_rapport', models.CharField(blank=True, max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rapport Comptabilité',
                'verbose_name_plural': 'Rapports Comptabilité',
            },
        ),
    ]
