# Generated by Django 5.2.3 on 2025-09-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_comptabilitereport'),
    ]

    operations = [
        # La colonne "association_enregistree" existe déjà dans la base.
        # On évite tout renommage physique de colonne qui provoque une duplication sous SQLite.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='eglise',
                    name='est_association',
                    field=models.BooleanField(
                        db_column='association_enregistree',
                        default=False,
                        verbose_name='Est une association enregistrée'
                    ),
                ),
            ],
        ),
    ]
