# Generated by Django 5.2.3 on 2025-09-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_eglise_est_association'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulteEffectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date du culte', verbose_name='Date')),
                ('hommes', models.PositiveIntegerField(default=0, verbose_name='Hommes')),
                ('femmes', models.PositiveIntegerField(default=0, verbose_name='Femmes')),
                ('filles', models.PositiveIntegerField(default=0, verbose_name='Enfants — Filles')),
                ('garcons', models.PositiveIntegerField(default=0, verbose_name='Enfants — Garçons')),
                ('nouveaux', models.PositiveIntegerField(default=0, verbose_name='Nouveaux')),
                ('total_enfants', models.PositiveIntegerField(default=0, verbose_name='Total enfants')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Effectif total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Effectif du culte',
                'verbose_name_plural': 'Effectifs du culte',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
