# Generated by Django 5.2.3 on 2025-09-09 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_culteeffectif'),
    ]

    operations = [
        migrations.AddField(
            model_name='culteeffectif',
            name='eglise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.eglise', verbose_name='Église'),
        ),
        migrations.AlterUniqueTogether(
            name='culteeffectif',
            unique_together={('eglise', 'date')},
        ),
    ]
