# Generated by Django 5.2.3 on 2025-09-09 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_culteeffectif_eglise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culteeffectif',
            name='eglise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eglise', verbose_name='Église'),
        ),
    ]
