# Generated by Django 5.2.3 on 2025-09-10 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_culteeffectif_eglise'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteHebdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'activité")),
                ('jour', models.CharField(choices=[('Dimanche', 'Dimanche'), ('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=20, verbose_name='Jour')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('duree_minutes', models.PositiveIntegerField(default=0, verbose_name='Durée (minutes)')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('responsable', models.CharField(blank=True, max_length=150, verbose_name='Responsable')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('eglise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.eglise', verbose_name='Église')),
            ],
            options={
                'verbose_name': 'Activité hebdomadaire',
                'verbose_name_plural': 'Activités hebdomadaires',
                'ordering': ['jour', 'heure_debut', 'nom'],
            },
        ),
    ]
