# Generated by Django 5.2.3 on 2025-09-12 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_activitehebdo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(blank=True, max_length=200, verbose_name='Département')),
                ('type_planification', models.CharField(choices=[('Annuelle', 'Annuelle'), ('Semestrielle', 'Semestrielle'), ('Trimestrielle', 'Trimestrielle'), ('Mensuelle', 'Mensuelle'), ('Hebdomadaire', 'Hebdomadaire')], max_length=20, verbose_name='Type de planification')),
                ('activite', models.CharField(max_length=255, verbose_name='Activité/Événement')),
                ('jour', models.CharField(choices=[('Dimanche', 'Dimanche'), ('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=20, verbose_name='Jour')),
                ('date_prev', models.DateField(verbose_name='Date prévisionnelle')),
                ('heure', models.TimeField(verbose_name='Heure')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('besoins', models.TextField(blank=True, verbose_name='Besoins logistiques')),
                ('responsable', models.CharField(blank=True, max_length=200, verbose_name='Responsable principal')),
                ('objectif', models.TextField(blank=True, verbose_name='Objectif')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Budget alloué')),
                ('statut', models.CharField(choices=[('À venir', 'À venir'), ('Confirmé', 'Confirmé'), ('Passé', 'Passé')], default='À venir', max_length=20, verbose_name='Statut')),
                ('nom_resp', models.CharField(max_length=200, verbose_name='Nom du responsable')),
                ('nom_pasteur', models.CharField(max_length=200, verbose_name='Nom du pasteur')),
                ('date_valid', models.DateField(verbose_name='Date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eglise', verbose_name='Église')),
            ],
            options={
                'verbose_name': 'Planification stratégique',
                'verbose_name_plural': 'Planifications stratégiques',
                'ordering': ['-date_prev', '-id'],
            },
        ),
    ]
