# Generated by Django 4.2.25 on 2026-01-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_strategicplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Matricule'),
        ),
    ]
